apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-sre-commander
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/siddiquiabdul007/ai-sre-commander.git
    targetRevision: main
    path: infrastructure/helm/ai-sre-commander
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sre-commander
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
